require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - .gems/**/*
    - bin/**/*
    - config/**/*
    - db/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - spec/**/*
    - config.ru
    - Guardfile
    - Rakefile
  RSpec:
    Patterns:
      - _spec.rb$

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 120

Bundler/OrderedGems:
  Enabled: false

Rails:
  Enabled: true
